version: 2
jobs:
  recs_api_check_version:
    working_directory: ~/services/recs-api
    docker:
      - image: cimg/go:1.18.1
    steps:
      - checkout
      - run: cd services/recs-api
      - run: make check-version

workflows:
  version: 2
  recs-api_install_test:
    jobs:
      - recs_api_check_version:
          filters:
            branches:
              ignore: master
