version: '3'
services:

  # ---
  # Stores
  # ---

  database:
    image: mysql:5.6.34
    environment:
      - MYSQL_ROOT_PASSWORD=pocockn
      - MYSQL_DATABASE=docker_pocockn
      - MYSQL_USER=pocockn
      - MYSQL_PASSWORD=pocockn
    expose:
      - 3306
    ports:
      - 3306:3306
  data-migrator:
    container_name: data-migrator
    build:
      context: ..
      dockerfile: core/database-migrator/Dockerfile
    networks:
      - recs-for-the-decks
    environment:
      - ENV=docker

  # ---
  # Services
  # ---

  recs-api:
    container_name: recs-api
    build:
      context: ..
      dockerfile: services/recs-api/Dockerfile
    networks:
      - recs-for-the-decks
    environment:
      - ENV=docker
    depends_on:
      - database
    links:
      - database:mysql
    expose:
      - 5000
  spotify-poller:
    container_name: spotify-poller
    build:
      context: ..
      dockerfile: services/spotify-poller/Dockerfile
    networks:
      - recs-for-the-decks
    environment:
      - ENV=docker
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    depends_on:
      - database
      - recs-api

networks:
  recs-for-the-decks:
