version: 2

orbs:
  path-filtering: circleci/path-filtering@0.0.2

jobs:
  spotify_poller_check_version:
    working_directory: ~/services/spotify-poller
    docker:
      - image: cimg/go:1.18.1
    steps:
      - checkout
      - run: cd services/spotify-poller; make check-version

workflows:
  setup:
  version: 2
  spotify_poller_install_test:
    jobs:
      - spotify_poller_check_version:
          filters:
            branches:
              ignore: master
      - path-filtering/filter:
          base-revision: master
          mapping: |
            VERSION modified_version true   
